default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  username: ran
  password: ranjan
  socket: /var/run/postgresql

development:
  <<: *default
  database: ionic_development

test:
  <<: *default
  database: ionic_test
  
production:
  <<: *default
  database: ionic_production
